name: fukiya
version: 0.2.0
author: Yulian Kuncheff <yulian@kuncheff.com>
description: A simple framework to improve and simplify the creation of server-side dart applications.
homepage: https://github.com/Daegalus/fukiya
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  logging: ">=0.9.0 < 0.10.0"
  crypto: ">=0.9.0 < 0.10.0"
  json: ">=0.9.0 < 0.10.0"
  log4dart: ">=1.4.11"
  mime: ">=0.9.0 < 0.10.0"
  http_server: ">=0.9.0 < 0.10.0"
