name: fukiya
version: 0.1.9
author: Yulian Kuncheff <yulian@kuncheff.com>
description: A simple framework to improve and simplify the creation of server-side dart applications.
homepage: https://github.com/Daegalus/fukiya
dependencies:
  formler: any
  unittest: any
  logging: any
  crypto: any
  static_file_handler:
    git:
      url: https://github.com/financeCoding/static-file-handler.git
      ref: update_latest_sdk